### PR TITLE
Integrated the NVD3 library and implemented a simple example chart on a card

### PR DESCRIPTION
**Pull request by stateoflux**
to see chart go to the #/charts route.

### CODE REVIEW

**Comment by sarchila** [comment]
WTF... need to select angular?

**Comment by Hendrixer** [comment]
You have to use"!" When choosing the version to write to the bower.json

**Comment by sarchila** [comment]
yeah WAYNE!!!  CMON!

**Comment by stateoflux** [comment]
My bad fellas!

**Pull request merged**
